# Generated by Django 3.1 on 2020-08-27 11:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_vr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base64', models.TextField(blank=True, help_text="Base 64 de l'image", null=True)),
                ('lastModified', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, help_text='le libelle de la visite', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visite_virtuelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, help_text='le libelle de la visite', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infospot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coords', models.CharField(help_text="coordonnées x, y et z de l'infospot", max_length=255)),
                ('info', models.TextField(help_text="Text/html de l'infospot")),
                ('txt_or_html', models.IntegerField(null=True)),
                ('img', models.ForeignKey(help_text="image où l'on verra le hotspot", on_delete=django.db.models.deletion.CASCADE, to='editor.image_vr')),
            ],
        ),
        migrations.AddField(
            model_name='image_vr',
            name='vr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.visite_virtuelle'),
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coords', models.CharField(help_text='coordonnées x, y et z du hotspot', max_length=255)),
                ('origin', models.ForeignKey(help_text="image où l'on verra le hotspot", on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='editor.image_vr')),
                ('to', models.ForeignKey(help_text='image sera où le hotspot redigera', on_delete=django.db.models.deletion.CASCADE, to='editor.image_vr')),
            ],
        ),
    ]
