# Generated by Django 3.1 on 2020-08-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20200827_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_vr',
            new_name='Image_360',
        ),
    ]
