# Generated by Django 3.1 on 2020-08-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20200827_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='coords',
            field=models.CharField(help_text='Coordonnées x, y et z du hotspot.', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='origin',
            field=models.ForeignKey(help_text="Image où l'on verra le hotspot.", on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='editor.image_360'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='to',
            field=models.ForeignKey(help_text='Image où  le hotspot redigera.', on_delete=django.db.models.deletion.CASCADE, to='editor.image_360'),
        ),
        migrations.AlterField(
            model_name='image_360',
            name='base64',
            field=models.TextField(blank=True, help_text="Base 64 de l'image.", null=True),
        ),
        migrations.AlterField(
            model_name='image_360',
            name='lastModified',
            field=models.IntegerField(help_text="La dernière modification effectuée par le user sur l'image au niveau de lui son pc.", null=True),
        ),
        migrations.AlterField(
            model_name='image_360',
            name='name',
            field=models.CharField(blank=True, help_text='Le libelle de la visite.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image_360',
            name='vr',
            field=models.ForeignKey(help_text='Visite virtuelle concernée à laquelle cette image est liée.', on_delete=django.db.models.deletion.CASCADE, to='editor.visite_virtuelle'),
        ),
        migrations.AlterField(
            model_name='infospot',
            name='coords',
            field=models.CharField(help_text="Coordonnées x, y et z de l'infospot.", max_length=255),
        ),
        migrations.AlterField(
            model_name='infospot',
            name='img',
            field=models.ForeignKey(help_text="Image où l'on verra l' infospot.", on_delete=django.db.models.deletion.CASCADE, to='editor.image_360'),
        ),
        migrations.AlterField(
            model_name='infospot',
            name='info',
            field=models.TextField(help_text="Text/html de l'infospot."),
        ),
        migrations.AlterField(
            model_name='infospot',
            name='txt_or_html',
            field=models.IntegerField(help_text="Donne le type de l'infospot(text = 0 et html = 1).", null=True),
        ),
        migrations.AlterField(
            model_name='visite_virtuelle',
            name='libelle',
            field=models.CharField(blank=True, help_text='Le libelle de la visite.', max_length=255, null=True),
        ),
    ]
