# Generated by Django 3.1 on 2020-08-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20200828_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_360',
            old_name='base64',
            new_name='base654',
        ),
    ]
