# Generated by Django 3.1 on 2020-08-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20200828_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_360',
            name='size',
            field=models.IntegerField(help_text="Taille de l'image.", null=True),
        ),
    ]
