# Generated by Django 3.1 on 2020-08-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20200828_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_360',
            name='lastModified',
            field=models.IntegerField(help_text="La dernière modification effectuée par le user sur l'image au niveau de lui son pc.", max_length=100, null=True),
        ),
    ]
