# Generated by Django 3.1 on 2020-08-28 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_auto_20200828_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image_360',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image_360',
            name='lastModified',
            field=models.IntegerField(help_text="La dernière modification effectuée par le user sur l'image au niveau de lui son pc.", null=True),
        ),
        migrations.AlterField(
            model_name='infospot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visite_virtuelle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
