# Generated by Django 3.1 on 2020-08-28 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0013_auto_20200828_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_360',
            name='lastModified',
            field=models.CharField(help_text="La dernière modification effectuée par le user sur l'image au niveau de lui son pc.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image_360',
            name='size',
            field=models.IntegerField(help_text="Taille de l'image.", null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
