# Generated by Django 3.1 on 2020-08-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0014_auto_20200828_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite_virtuelle',
            name='libelle',
            field=models.CharField(blank=True, default='vide', help_text='Le libelle de la visite.', max_length=255),
        ),
    ]
