# Generated by Django 2.2.9 on 2020-09-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0018_auto_20200902_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_360',
            name='vr',
            field=models.ForeignKey(help_text='Visite virtuelle concernée à laquelle cette image est liée.', on_delete=django.db.models.deletion.CASCADE, related_name='vr', to='editor.Visite_virtuelle'),
        ),
    ]
