# Generated by Django 2.2.9 on 2020-09-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0021_auto_20200903_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='origin',
            field=models.ForeignKey(help_text="Image où l'on verra le hotspot.", on_delete=django.db.models.deletion.CASCADE, related_name='hotspot', to='editor.Image_360'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='to',
            field=models.ForeignKey(help_text='Image où  le hotspot redigera.', on_delete=django.db.models.deletion.CASCADE, related_name='hotpost_to', to='editor.Image_360'),
        ),
    ]
